name: laijau
description: A ride sharing application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # Map & Location
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  flutter_polyline_points: ^2.0.1
  
  # Networking
  dio: ^5.4.0
  socket_io_client: ^2.0.3
  http: ^1.2.0
  
  # Video Call
  jitsi_meet_flutter_sdk:
    path: .local_plugins/jitsi_meet_flutter_sdk
  
  # State Management
  provider: ^6.1.1
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Utilities
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.2.4
  image_picker: ^1.0.7
  permission_handler: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# Dependency overrides to fix Android v1 embedding issue with Flutter 3.38+
dependency_overrides:
  flutter_plugin_android_lifecycle:
    path: .local_plugins/flutter_plugin_android_lifecycle-2.0.33
  geolocator_android:
    path: .local_plugins/geolocator_android-4.6.2
  image_picker_android:
    path: .local_plugins/image_picker_android-0.8.13+10
  permission_handler_android:
    path: .local_plugins/permission_handler_android-12.1.0
  shared_preferences_android:
    path: .local_plugins/shared_preferences_android-2.4.18
  url_launcher_android:
    path: .local_plugins/url_launcher_android-6.3.28

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
